services:
  frontend:
    build: ./frontend
    container_name: ticktack-frontend
    ports:
      - "8001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./certs:/certs        # Zertifikate ins Container-FileSystem mounten
    command: npm run dev -- --host
    environment:
      - VITE_BACKEND_URL=https://localhost:5000

  backend:
    build: ./backend
    container_name: ticktack-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    command: node server.js
    volumes:
      - ./certs:/certs

  db:
    image: mysql:5.7
    container_name: ticktack-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticktack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
